[package]
name = "omnichat"
version = "1.1.4"
description = "Omnichat, an all-in-one LLM chat application"
authors = ["cyborgoat"]
license = "MIT"
repository = "https://github.com/cyborgoat/omnichat"
edition = "2021"
rust-version = "1.80"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2", features = ["codegen"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.5", features = [] }
tauri-plugin-log = "2.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream", "rustls-tls"] }
futures-util = "0.3"
url = "2.0"
anyhow = "1.0"
regex = "1.0"
